# Keys usados na interface do Menu Principal do Front

# Clock Button key
CLOCK_BUTTON_KEY = '-CLOCK_BUTTON_KEY-'

# Pipeline Buttons key
PIPELINE_BUTTON1_KEY = '-PIPELINE_BUTTON1_KEY-'
PIPELINE_BUTTON2_KEY = '-PIPELINE_BUTTON2_KEY-'
PIPELINE_BUTTON3_KEY = '-PIPELINE_BUTTON3_KEY-'
PIPELINE_BUTTON4_KEY = '-PIPELINE_BUTTON4_KEY-'
PIPELINE_BUTTON5_KEY = '-PIPELINE_BUTTON5_KEY-'
PIPELINE_BUTTON6_KEY = '-PIPELINE_BUTTON6_KEY-'
PIPELINE_BUTTON7_KEY = '-PIPELINE_BUTTON7_KEY-'
PIPELINE_BUTTON8_KEY = '-PIPELINE_BUTTON8_KEY-'

# Banco de Registradores Key
BANCO_REGISTRADOR_KEY1_TEXT = '-BANCO_REGISTRADOR_KEY1_TEXT-'
BANCO_REGISTRADOR_KEY2_TEXT = '-BANCO_REGISTRADOR_KEY2_TEXT-'
BANCO_REGISTRADOR_KEY3_TEXT = '-BANCO_REGISTRADOR_KEY3_TEXT-'
BANCO_REGISTRADOR_KEY4_TEXT = '-BANCO_REGISTRADOR_KEY4_TEXT-'
BANCO_REGISTRADOR_KEY5_TEXT = '-BANCO_REGISTRADOR_KEY5_TEXT-'
BANCO_REGISTRADOR_KEY6_TEXT = '-BANCO_REGISTRADOR_KEY6_TEXT-'
BANCO_REGISTRADOR_KEY7_TEXT = '-BANCO_REGISTRADOR_KEY7_TEXT-'
BANCO_REGISTRADOR_KEY8_TEXT = '-BANCO_REGISTRADOR_KEY8_TEXT-'
SELECTED_BANCO_REGISTRADOR_KEY = '0'