# Textos usados na tela do Front

# Window title
FRONT_TITLE_WINDOW_TEXT = 'Tomasulo Visual'

# Clock Button text
CLOCK_BUTTON_TEXT = 'Clock'

# Pipeline Buttons
PIPELINE_BUTTON1_TEXT = ''
PIPELINE_BUTTON2_TEXT = ''
PIPELINE_BUTTON3_TEXT = ''
PIPELINE_BUTTON4_TEXT = ''
PIPELINE_BUTTON5_TEXT = ''
PIPELINE_BUTTON6_TEXT = ''
PIPELINE_BUTTON7_TEXT = ''
PIPELINE_BUTTON8_TEXT = ''

# Banco de Registradores Buttons
BANCO_REGISTRADOR_BUTTON1_TEXT = '0'
BANCO_REGISTRADOR_BUTTON2_TEXT = '0'
BANCO_REGISTRADOR_BUTTON3_TEXT = '0'
BANCO_REGISTRADOR_BUTTON4_TEXT = '0'
BANCO_REGISTRADOR_BUTTON5_TEXT = '0'
BANCO_REGISTRADOR_BUTTON6_TEXT = '0'
BANCO_REGISTRADOR_BUTTON7_TEXT = '0'
BANCO_REGISTRADOR_BUTTON8_TEXT = '0'